import json
import csv
from sentence_transformers import SentenceTransformer, util

SIMILARITY_THRESHOLD = 0.5  # Adjust this value as needed

if __name__ == '__main__':
    sentences = [
        "She rode her bicycle through the park every morning.",
        "The bicycle leaned against the old oak tree.",
        "He fixed a flat tire on his bicycle after school.",
        "The red bicycle was a birthday gift from his grandparents.",
        "They went on a bicycle tour across Europe.",
        "Her bicycle had a basket full of flowers.",
        "The bicycle chain slipped off during the uphill climb.",
        "He stored his bicycle in the garage next to the lawnmower.",
        "A new bicycle can be quite expensive.",
        "The child learned to ride a bicycle without training wheels.",
        "She bought a folding bicycle for her commute.",
        "The bicycle path follows the river all the way downtown.",
        "A bicycle bell rang from around the corner.",
        "His bicycle had glowing LED lights on the spokes.",
        "The stolen bicycle was found a week later.",
        "I rode my bicycle to the library.",
        "A bicycle repair shop opened near the university.",
        "The bicycle race drew a large crowd.",
        "He balanced carefully as he mounted the bicycle.",
        "The old bicycle had rust on the frame.",
        "She wore a helmet while riding her bicycle.",
        "A bicycle courier sped past us on the sidewalk.",
        "The tandem bicycle looked like a lot of fun.",
        "We rented bicycles and explored the countryside.",
        "His bicycle chain snapped mid-ride.",
        "The bicycle trail led deep into the forest.",
        "Her bicycle had pink streamers on the handlebars.",
        "The museum displayed a vintage penny-farthing bicycle.",
        "I locked my bicycle to the rack outside the café.",
        "The boy's first bicycle was bright green.",
        "He performed a trick on his BMX bicycle.",
        "She used her bicycle to get to work every day.",
        "A bicycle tire squeaked as it turned.",
        "The bicycle frame was made of lightweight carbon fiber.",
        "He stored his bicycle on a wall-mounted hook.",
        "A bicycle parade rolled down Main Street.",
        "Her bicycle ride was interrupted by a sudden downpour.",
        "The bicycle bell jingled cheerfully.",
        "He rode his bicycle in the annual charity event.",
        "The park is a perfect place for a bicycle picnic.",
        "A group of kids raced their bicycles around the block.",
        "She decorated her bicycle with lights for the festival.",
        "The police officer followed the suspect on a bicycle.",
        "I found an abandoned bicycle in the alley.",
        "A bicycle helmet is essential for safety.",
        "He modified his bicycle for long-distance touring.",
        "The bicycle ride gave him a sense of freedom.",
        "Her bicycle was stolen from the train station.",
        "The bicycle club meets every Saturday morning.",
        "A man balanced three boxes on the back of his bicycle.",
        "The bicycle trail winds through beautiful scenery.",
        "He added a basket to his bicycle for groceries.",
        "A bicycle pump hung from the garage wall.",
        "His bicycle squeaked with every pedal stroke.",
        "She wheeled her bicycle into the elevator.",
        "The bicycle glided smoothly down the hill.",
        "A bicycle license plate hung from the rear fender.",
        "He cleaned the mud off his bicycle after the ride.",
        "The bicycle basket carried a loaf of bread and some apples.",
        "They customized their bicycle with stickers and paint.",
        "She replaced the worn-out tires on her bicycle.",
        "The bicycle handlebar grips were peeling.",
        "He coasted downhill on his bicycle with no hands.",
        "A bicycle mechanic tuned up the gears and brakes.",
        "The new bicycle lock is virtually unbreakable.",
        "They donated a bicycle to a local charity.",
        "The bicycle tour lasted five days and covered 200 miles.",
        "He slipped on the wet pavement while riding his bicycle.",
        "Her bicycle horn was shaped like a duck.",
        "The police officer rode a bicycle through the park.",
        "She taught her little brother how to ride a bicycle.",
        "He jumped a ramp on his bicycle at the skatepark.",
        "The bicycle bell echoed through the narrow alley.",
        "His old bicycle still rides like new.",
        "The bicycle leaned awkwardly against the fence.",
        "She found a bicycle route that avoided traffic.",
        "The tandem bicycle made them laugh as they wobbled together.",
        "He bought a secondhand bicycle for a good price.",
        "The bicycle frame cracked during the crash.",
        "A squirrel darted in front of his bicycle.",
        "The girl’s bicycle had training wheels on it.",
        "The bicycle's front tire was completely flat.",
        "A bicycle messenger delivered the package right on time.",
        "He repaired the bicycle with a multitool.",
        "Her bicycle had gears that shifted effortlessly.",
        "The new bicycle trail opened last weekend.",
        "They rode their bicycles along the beach.",
        "A bicycle basket isn’t just for carrying things—it adds charm too.",
        "His mountain bicycle handled rough terrain with ease.",
        "She carried her bicycle up the stairs.",
        "The bicycle horn honked loudly in the busy street.",
        "The bicycle shop was offering tune-up discounts.",
        "He wrapped his bicycle in lights for the night ride.",
        "A bicycle shadow followed him across the sidewalk.",
        "Her favorite childhood memory was learning to ride a bicycle.",
        "The bicycle path was blocked by a fallen tree.        ",
        "They took a selfie with their bicycles in front of the sunset.",
        "The bicycle spun out on the gravel.",
        "His bicycle commute was faster than driving.",
        "The bicycle lay quietly in the grass, waiting for its next ride",

        "He bought his first motorcycle at the age of eighteen.",
        "The motorcycle sped past the traffic with a deafening roar.",
        "She learned to ride a motorcycle before she could drive a car.",
        "The old motorcycle still runs, though it rattles like a skeleton.",
        "They went on a cross-country motorcycle trip last summer.",
        "A black motorcycle stood parked outside the diner.",
        "The motorcycle leaned sharply as he turned the corner.",
        "His dream was to ride a motorcycle along the Pacific Coast Highway.",
        "The sound of the motorcycle echoed through the canyon.",
        "She revved the motorcycle and disappeared into the mist.",
        "That motorcycle is custom-built for racing.",
        "He wore a leather jacket to match his motorcycle.",
        "The motorcycle skidded slightly on the wet pavement.",
        "A sleek red motorcycle caught everyone's attention.",
        "They rode the motorcycle through winding mountain roads.",
        "The motorcycle’s engine purred like a content cat.",
        "He fell off the motorcycle but walked away unhurt.",
        "She prefers a motorcycle over a car any day.",
        "A gang of motorcycle riders roared into town.",
        "His motorcycle license had just arrived in the mail.",
        "The motorcycle had flame decals down the side.",
        "There was a motorcycle parked in every driveway.",
        "He sold his motorcycle to pay for college.",
        "A loud motorcycle backfired outside the window.",
        "She rode the motorcycle barefoot across the desert.",
        "The vintage motorcycle was worth a small fortune.",
        "He kept his motorcycle polished to a mirror shine.",
        "The motorcycle club held weekly meetups downtown.",
        "They repaired the motorcycle together in the garage.",
        "The motorcycle helmet was decorated with stickers.",
        "That motorcycle can go from 0 to 60 in four seconds.",
        "He designed his own electric motorcycle prototype.",
        "The stolen motorcycle was found abandoned in the woods.",
        "I saw a dog riding in the sidecar of a motorcycle.",
        "The motorcycle rumbled as she turned the key.",
        "It was his father's old motorcycle, restored to glory.",
        "A motorcycle zipped between lanes on the freeway.",
        "The motorcycle’s headlight lit up the foggy road.",
        "She received a motorcycle as a graduation gift.",
        "The motorcycle shop had a wall of shiny helmets.",
        "He bought a new motorcycle jacket with reinforced padding.",
        "The roar of the motorcycle startled the cat.",
        "She dreamed of traveling Europe on a motorcycle.",
        "A child pointed excitedly at the bright yellow motorcycle.",
        "The motorcycle slid out from under him on the ice.",
        "He rebuilt the motorcycle engine completely by himself.",
        "The motorcycle convoy stretched for half a mile.",
        "His father used to race motorcycles professionally.",
        "She was the only girl in the motorcycle stunt show.",
        "The motorcycle show drew a massive crowd.",
        "He wiped down the motorcycle after every ride.",
        "Her motorcycle gloves were lined with soft leather.",
        "That motorcycle can outrun most sports cars.",
        "He felt most alive on the back of a motorcycle.",
        "The motorcycle's exhaust rattled the windows.",
        "The motorcycle tour covered five national parks.",
        "A license plate hung loosely on the motorcycle.",
        "Her hair whipped wildly as the motorcycle gained speed.",
        "The motorcycle exhibition featured bikes from every decade.",
        "He lost control of the motorcycle on the sharp curve.",
        "The motorcycle was his pride and joy.",
        "She revved the motorcycle just to hear it growl.",
        "His garage was filled with motorcycle parts and tools.",
        "A bright neon motorcycle sign lit up the bar.",
        "The motorcycle lane was clogged with morning traffic.",
        "He carried his gear in motorcycle saddlebags.",
        "A motorcycle cop pulled them over for speeding.",
        "The motorcycle rally raised money for veterans.",
        "He watched the sunset from his parked motorcycle.",
        "Her motorcycle boots clicked against the pavement.",
        "The motorcycle café was a popular biker hangout.",
        "He covered the motorcycle before the rain started.",
        "A custom paint job gave the motorcycle personality.",
        "The motorcycle growled as he twisted the throttle.",
        "She loved the freedom her motorcycle gave her.",
        "The motorcycle broke down in the middle of nowhere.",
        "They posed for a photo next to the motorcycle.",
        "He surprised her with a motorcycle ride along the coast.",
        "The motorcycle engine sputtered before coming to life.",
        "A line of motorcycle headlights pierced the night.",
        "His first motorcycle was a rusty old Honda.",
        "The motorcycle drifted sideways in the dirt.",
        "A trail of dust followed the speeding motorcycle.",
        "He stashed tools in a hidden motorcycle compartment.",
        "The motorcycle accident was all over the news.",
        "Her motorcycle had a vintage charm that turned heads.",
        "The motorcycle flew over the ramp in a perfect arc.",
        "He kept a miniature motorcycle model on his desk.",
        "The motorcycle’s paint job reflected the desert sun.",
        "She used her motorcycle to commute every day.",
        "A rider popped a wheelie on his motorcycle downtown.",
        "The motorcycle chain needed to be tightened.",
        "His motorcycle gloves smelled like oil and leather.",
        "The motorcycle tire left a streak on the gravel.",
        "She built her motorcycle from scratch.",
        "He heard a motorcycle rumbling in the distance.",
        "The motorcycle hugged every curve of the winding road.",
        "Her motorcycle was faster than it looked.",
        "They raced their motorcycles across the salt flats.",
        "The motorcycle disappeared over the hill, leaving only dust behind."

        "A man is playing a guitar",
        "A man is playing the guitar",
        "A guy is playing a guitar",
        "A guy is playing the guitar",
        "The man is playing a guitar",
        "The man is playing the guitar",
        "A man is strumming a guitar",
        "A man is strumming the guitar",
        "A man is playing an electric guitar",
        "A man is playing the electric guitar",
        "A man is playing acoustic guitar",
        "A man is playing the acoustic guitar",
        "A man is performing with a guitar",
        "A man is performing with the guitar",
        "A musician is playing a guitar",
        "A musician is playing the guitar",
        "A man plays a guitar",
        "A man plays the guitar",
        "A man is holding a guitar and playing",
        "A man is plucking a guitar",
        "A man is playing music on a guitar",
        "A man is playing music on the guitar",
        "A man is playing a song on the guitar",
        "A man is playing a tune on the guitar",
        "A man is using a guitar to play music",
        "A man is jamming on the guitar",
        "A man is jamming with a guitar",
        "A man is playing a solo on the guitar",
        "A man is playing chords on the guitar",
        "A man is playing riffs on a guitar",
        "A man is playing softly on a guitar",
        "A man is playing loudly on a guitar",
        "A man is playing blues on a guitar",
        "A man is playing jazz on a guitar",
        "A man is playing rock music on a guitar",
        "A man is playing a melody on the guitar",
        "A man is playing the guitar in a room",
        "A man is playing the guitar outside",
        "A man is playing the guitar on stage",
        "A man is playing the guitar at a concert",
        "A man is playing a guitar on the street",
        "A man is sitting and playing a guitar",
        "A man is standing and playing a guitar",
        "A man is casually playing a guitar",
        "A man is expertly playing the guitar",
        "A man is skillfully playing a guitar",
        "A man is gently playing a guitar",
        "A man is passionately playing the guitar",
        "A man is happily playing a guitar",
        "A man is focused while playing the guitar",
        "A male guitarist is playing a guitar",
        "A male guitarist is playing the guitar",
        "A man is playing a guitar at home",
        "A man is playing a guitar in the park",
        "A man is playing guitar by the beach",
        "A man is playing a red guitar",
        "A man is playing a shiny guitar",
        "A man is playing a worn-out guitar",
        "A man is playing a vintage guitar",
        "A man is playing a new guitar",
        "A man is tuning and playing a guitar",
        "A man is learning to play the guitar",
        "A man is practicing with a guitar",
        "A man is rehearsing on the guitar",
        "A man is strumming chords on a guitar",
        "A man is fingerpicking on the guitar",
        "A man is using a pick to play the guitar",
        "A man is playing a guitar for fun",
        "A man is playing a guitar for an audience",
        "A man is playing a guitar to entertain",
        "A man is playing guitar for a crowd",
        "A man is playing guitar for a friend",
        "A man is playing guitar with emotion",
        "A man is playing guitar with intensity",
        "A man is playing guitar in the rain",
        "A man is playing guitar under the sun",
        "A man is playing guitar in the spotlight",
        "A man is playing guitar in the background",
        "A man is recording while playing guitar",
        "A man is being filmed playing the guitar",
        "A man is playing guitar for a video",
        "A man is playing a song on his guitar",
        "A man is playing his favorite guitar",
        "A man is playing a familiar tune on guitar",
        "A man is playing music with a guitar",
        "A man is lost in playing the guitar",
        "A man is immersed in guitar playing",
        "A man is fully engaged playing guitar",
        "A man is improvising on the guitar",
        "A man is accompanying vocals on the guitar",
        "A man is playing rhythm guitar",
        "A man is playing lead guitar",
        "A man is playing the guitar with style",
        "A man is playing the guitar confidently",
        "A man is playing the guitar effortlessly",
        "A man is playing the guitar alone",
        "A man is playing the guitar with others",
        "A man is playing the guitar in a band",
        "A man is playing the guitar next to a fire",
        "A man is playing the guitar near a window"
    ]

    model = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = model.encode(sentences, convert_to_tensor=True)
    cosine_scores = util.cos_sim(embeddings, embeddings)

    pairs = []
    for i in range(len(sentences)):
        for j in range(len(sentences)):
            similarity = cosine_scores[i][j].item()
            pairs.append({
                "sentence1": sentences[i],
                "sentence2": sentences[j],
                "similarity": similarity,
                "is_similar": similarity >= SIMILARITY_THRESHOLD
            })

    fileName = 'sentence_similarities_bike_motorcyle_guitar';
    # Save to JSON
    with open(fileName+'.json', 'w') as f:
        json.dump(pairs, f, indent=2)

    # Save to CSV
    with open(fileName+'.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=["sentence1", "sentence2", "similarity", "is_similar"])
        writer.writeheader()
        writer.writerows(pairs)